#!/usr/bin/env python

import pickle
import pandas as pd

obj = pickle.load(open("vector.DOMAINS"))
print obj

# for v in obj:
    

    # Calc max prob
#     prob = 0
#     for i in range(4, len(v)):
#         if v[i] > prob: prob = v[i]

#     if prob > 0.00:
#     print v[0], v[1], v[2], v[3], prob

