#!/usr/bin/env python

# Displays ...

# Runs GetElements to perform a query, and then uses Limit to restrict the
# data set to 15.

import requests
import json
import sys
from gaffer import Gaffer

query = {
  "class": "uk.gov.gchq.gaffer.operation.OperationChain",
  "operations": [
    {
      "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements",
            "view": {
                "edges": {
                },
                "entities": {
                }
            }
     
    }
  ]
}

g = Gaffer("https://analytics.trustnetworks.com/gaffer-threat")
g.use_cert()

url = "/rest/v2/graph/operations/execute"
  
res = g.post(url, data=json.dumps(query))

print json.dumps(res.json(), indent=4)

