#!/usr/bin/env python

import json
from gaffer import Gaffer

gaffer_url = "https://analytics.trustnetworks.com/gaffer-threat"

g = Gaffer(gaffer_url)
g.use_cert()

op = g.get_all(entities=["domain"], edges=None)
r = g.execute_chunked(op)

for v in r:
    try:
        o = json.loads(v)
    except:
        pass
    print o["vertex"]

