#!/usr/bin/env python

import json
import gaffer

gaffer_url = "https://analytics.trustnetworks.com/gaffer-threat"

g = gaffer.Gaffer(gaffer_url)
g.use_cert()

op = gaffer.GetAllElements(entities=[gaffer.ViewGroup("domain")], edges=None)
r = g.execute_chunked(op)

for v in r:
    try:
        o = json.loads(v)
    except:
        pass
    print o["vertex"]

