#!/usr/bin/env python

# Displays ...

# Runs GetElements to perform a query, and then uses Limit to restrict the
# data set to 15.

from gaffer import Gaffer

g = Gaffer("https://analytics.trustnetworks.com/gaffer-threat")
g.use_cert()
op = g.get_all()
ops = g.operation_list([op])
res = g.execute_chunked(ops)

print "["

sep=""

i = 0
for v in res:

    if v == "": continue

    print sep
    sep =","
    print v

print "]"

res.close()

