#!/usr/bin/env python

# Displays ...

# Runs GetElements to perform a query, and then uses Limit to restrict the
# data set to 15.

import requests
import json
import sys
import threatgraph
from tabulate import tabulate

query = {
    "class": "uk.gov.gchq.gaffer.operation.OperationChain",
    "operations": [
        {
            "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements",
            "view": {
                "edges": {
                    "matches": {}
                },
                "entities": {
                    "blacklist": {}
                }
            }
        }
    ]
}

g = threatgraph.Gaffer()
g.use_cert()

url = "/rest/v2/graph/operations/execute"
res = g.post(url, data=json.dumps(query))

obj = res.json()

prob = {}
src = {}
for o in obj:
    if o["group"] == "blacklist":
        prob[o["vertex"]] = o["properties"]["probability"]
        src[o["vertex"]] = o["properties"]["source"]

data = []        

for o in obj:
    if o["group"] == "matches":
        thing = o["source"]
        bl = o["destination"]
        p = prob.get(bl, 0.0)
        s = src.get(bl, "")
        d = o["properties"]["description"]
        data.append([thing, s, p, bl, d])

print tabulate(data, headers=["origin", "source", "probability", "blacklist", "desc"])

