#!/usr/bin/env python3

import sys
import updater

try:
    
    # Get Threat Graph
    u = updater.FacebookUpdater.domain_updater()
    u.update()

except Exception as e:

    print(e)
    sys.exit(1)

