#!/usr/bin/env python

# Displays ...

# Runs GetElements to perform a query, and then uses Limit to restrict the
# data set to 15.

import requests
import json
import sys
from gaffer import Gaffer
from tabulate import tabulate

query = {
    "class": "uk.gov.gchq.gaffer.operation.OperationChain",
    "operations": [
        {
            "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements",
            "view": {
                "entities": {
                    "ip": {
                        "excludeProperties" : [ "count", "time" ]
                    }
                }
            }
            
        },
        {
            "class" : "uk.gov.gchq.gaffer.operation.impl.GetWalks",
            "operations" : [
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "ipflow": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "matches": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                }
            ],
            "resultsLimit" : 1000000
        }
        
  ]
}

g = Gaffer("https://analytics.trustnetworks.com/gaffer-threat")
g.use_cert()

url = "/rest/v2/graph/operations/execute"

res = g.post(url, data=json.dumps(query))
res = res.json()

data = [
    [ent["entities"][0].keys()[0], ent["entities"][1].keys()[0],
     ent["entities"][2].keys()[0]]
    for ent in res
]

print tabulate(data, headers=["src", "dest", "block"])

