#!/usr/bin/env python

# Displays ...

# Runs GetElements to perform a query, and then uses Limit to restrict the
# data set to 15.

import requests
import json
import sys
import pandas as pd
from gaffer import Gaffer

query = {
    "class": "uk.gov.gchq.gaffer.operation.OperationChain",
    "operations": [
        {
            "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements",
            "view": {
                "entities": {
                    "ip": {
                        "excludeProperties" : [ "count", "time" ]
                    }
                }
            }
            
        },
        {
            "class" : "uk.gov.gchq.gaffer.operation.impl.GetWalks",
            "operations" : [
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "ipflow": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "serves": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "indomain": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    "class" : "uk.gov.gchq.gaffer.operation.OperationChain",
                    "operations" : [
                        {
                            "class" : "uk.gov.gchq.gaffer.operation.impl.get.GetElements",
                            "includeIncomingOutGoing" : "OUTGOING",
                            "view": {
                                "edges": {
                                    "matches": {
                                        "excludeProperties" : [ "count", "time" ]
                                    }
                                }
                            }
                        }
                    ]
                }
            ],
            "resultsLimit" : 1000000
        }
        
  ]
}

g = Gaffer("https://analytics.trustnetworks.com/gaffer-threat")
g.use_cert()

url = "/rest/v2/graph/operations/execute"

res = g.post(url, data=json.dumps(query))
res = res.json()

src = [ent["entities"][0].keys()[0] for ent in res]
dest = [ent["entities"][1].keys()[0] for ent in res]
server = [ent["entities"][2].keys()[0] for ent in res]
domain = [ent["entities"][3].keys()[0] for ent in res]
blocklist = [ent["entities"][4].keys()[0] for ent in res]

df = pd.DataFrame(
    {
        "src": src, "dest": dest, "server": server, "domain": domain,
        "blocklist": blocklist
    },
    columns=["src", "dest", "server", "domain", "blocklist"]
)

print df[["src", "dest", "domain", "blocklist"]]

